#ifndef GRAMMARVAR_H
// grammar variable definition
#define PROGRAM 0
#define SUBPROGRAM_DECLARATIONS -1
#define IDENTIFIER_LIST -2
#define DECLARATIONS -3
#define COMPOUND_STATEMENT -4
#define DECLARATION -5
#define TYPE -6
#define STANDARD_TYPE -7
#define SUBPROGRAM_DECLARATION -8
#define SUBPROGRAM_HEAD -9
#define ARGUMENTS -10
#define PARAMETER_LIST -11
#define OPTIONAL_STATEMENTS -12
#define STATEMENT_LIST -13
#define STATEMENT -14
#define PROCEDURE_STATEMENT -15
#define VARIABLE -16
#define EXPRESSION -17
#define EXPRESSION_LIST -18
#define SIMPLE_EXPRESSION -19
#define TERM -20
#define FACTOR -21
#define SIGN -22
#endif // GRAMMARVAR_H
