#ifndef GRAMMARVAR_H
// grammar variable definition
#define PROGRAM -1
#define SUBPROGRAM_DECLARATIONS -2
#define IDENTIFIER_LIST -3
#define DECLARATIONS -4
#define COMPOUND_STATEMENT -5
#define DECLARATION -6
#define TYPE -7
#define STANDARD_TYPE -8
#define SUBPROGRAM_DECLARATION -9
#define SUBPROGRAM_HEAD -10
#define ARGUMENTS -11
#define PARAMETER_LIST -12
#define OPTIONAL_STATEMENTS -13
#define STATEMENT_LIST -14
#define STATEMENT -15
#define PROCEDURE_STATEMENT -16
#define VARIABLE -17
#define EXPRESSION -18
#define EXPRESSION_LIST -19
#define SIMPLE_EXPRESSION -20
#define TERM -21
#define FACTOR -22
#define SIGN -23
#endif // GRAMMARVAR_H
