#ifndef GRAMMARVAR_H
// grammar variable definition
#define PROGRAM -1
#define SUBPROGRAM_DECLARATIONS -2
#define IDENTIFIER_LIST -3
#define DECLARATIONS -4
#define COMPOUND_STATEMENT -5
#define DECLARATION -6
#define TYPE -7
#define STANDARD_TYPE -8
#define M -9
#define SUBPROGRAM_DECLARATION -10
#define SUBPROGRAM_HEAD -11
#define ARGUMENTS -12
#define PARAMETER_LIST -13
#define OPTIONAL_STATEMENTS -14
#define STATEMENT_LIST -15
#define STATEMENT -16
#define PROCEDURE_STATEMENT -17
#define VARIABLE -18
#define EXPRESSION -19
#define EXPRESSION_LIST -20
#define SIMPLE_EXPRESSION -21
#define TERM -22
#define FACTOR -23
#define SIGN -24
#endif // GRAMMARVAR_H
